# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bdef44df56b1d3be2ea154866156b476488e7d79b2ccf84961a2d59e8a4a072e9f5d6265f66d5624a86b3fc530f0a0d3dac423e397fb807e629b5c03a0f9c89

test:
  secret_key_base: a4f3823780160f3e05c6740abe6cbece2511808ee765773698752b3ddbcfa0d4e654121a4c80478f7a3de83a84c08efa532b0c14e08b57d7e2d877ffdb16e7d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
